spring.application.name=jgog-core

# Hides the Spring Boot banner
spring.main.banner-mode=off
spring.main.log-startup-info=false

# Suppresses unnecessary logs
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.com.zaxxer.hikari=ERROR
logging.level.org.springframework.data=ERROR

# Keeps your own logs visible
logging.level.es.ddmain.jgogcore=INFO
